server:
  port: 5678

spring:
  application:
    name: sidecar

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    preferIpAddress: true

sidecar:
  port: 8080
  health-uri: http://localhost:8080/health.json
  accept-all-ssl-certificates: true
